config/routes.rb
Rails.application.routes.draw do
  resources :labs
  resources :snippets
  devise_for :users
  resources :users

  mount ActionCable.server => '/cable'
  root 'welcome#welcome'

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "signup" => "devise/registrations#new"
    get "logout" => "devise/sessions#destroy"
  end
  

end

app/models/lab.rb
class Lab < ActiveRecord::Base
  has_many :snippets
  has_many :users, through: :snippets
  belongs_to :admin, :class_name => :User, :foreign_key => "user_id"

  validates_presence_of :name
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base

  belongs_to :user
  belongs_to :lab

  validates_presence_of :content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :email

  has_many :snippets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController

  def index
  end

  def new
    @lab = Lab.new
  end

  def create
    @lab = Lab.create(lab_params)
    @lab.admin = current_user
    @lab.save

    redirect_to labs_path(@lab)
  end

  def show
    @lab = Lab.find(params[:id])
    @snippet = Snippet.new
  end

  private
    def lab_params
      params.require(:lab).permit(:name, :description)
    end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def create
    @snippet = Snippet.create(snippet_params)
    @snippet.user = current_user
    @snippet.lab = Lab.find(params[:snippet][:lab])
    @snippet.save
   ActionCable.server.broadcast 'snippets',
    snippet: @snippet.content,
    user: @snippet.user

    head :ok
  end

  private

    def snippet_params
      params.require(:snippet).permit(:content)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/labs/index.html.erb
index.html.erb

app/views/labs/new.html.erb
Create a new lab!

<%=form_for(@lab) do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name %>
  <%=f.label :description%>
  <%=f.text_field :description %>
  <%=f.submit "create"%>
<%end%>

app/views/labs/show.html.erb
<h1><%=@lab.name%></h1>
<h2><%=@lab.description%></h2>

<div id="snippets">

</div>
<script type="text/javascript">

</script>
<button id="create-snippet">submit</button>


Add your snippet!

<%=form_for @snippet, :remote=> true do |f|%>
  <%=f.label :content%>
  <%=f.text_area :content %>
  <%=f.hidden_field :lab, value: @lab.id%>
  <%=f.submit "create"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeParty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/welcome.html.erb
<%=link_to "view labs", labs_path%>

<%=link_to "create lab", new_lab_path%>